from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 191, 41))
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 70, 241, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Number3Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number3Button.setObjectName("Number3Button")
        self.gridLayout.addWidget(self.Number3Button, 3, 3, 1, 1)
        self.Number1Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number1Button.setObjectName("Number1Button")
        self.gridLayout.addWidget(self.Number1Button, 3, 0, 1, 1)
        self.SubmitButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.SubmitButton.setObjectName("SubmitButton")
        self.gridLayout.addWidget(self.SubmitButton, 4, 3, 1, 1)
        self.ClearButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.gridLayout.addWidget(self.ClearButton, 4, 0, 1, 1)
        self.Number9Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number9Button.setObjectName("Number9Button")
        self.gridLayout.addWidget(self.Number9Button, 0, 3, 1, 1)
        self.NextButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout.addWidget(self.NextButton, 4, 2, 1, 1)
        self.Number8Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number8Button.setObjectName("Number8Button")
        self.gridLayout.addWidget(self.Number8Button, 0, 2, 1, 1)
        self.DivideButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.DivideButton.setObjectName("DivideButton")
        self.gridLayout.addWidget(self.DivideButton, 0, 4, 1, 1)
        self.MultiplyButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.MultiplyButton.setObjectName("MultiplyButton")
        self.gridLayout.addWidget(self.MultiplyButton, 2, 4, 1, 1)
        self.AdditionButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.AdditionButton.setObjectName("AdditionButton")
        self.gridLayout.addWidget(self.AdditionButton, 4, 4, 1, 1)
        self.SubtractButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.SubtractButton.setObjectName("SubtractButton")
        self.gridLayout.addWidget(self.SubtractButton, 3, 4, 1, 1)
        self.Number4Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number4Button.setObjectName("Number4Button")
        self.gridLayout.addWidget(self.Number4Button, 2, 0, 1, 1)
        self.Number6Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number6Button.setObjectName("Number6Button")
        self.gridLayout.addWidget(self.Number6Button, 2, 3, 1, 1)
        self.Number5Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number5Button.setObjectName("Number5Button")
        self.gridLayout.addWidget(self.Number5Button, 2, 2, 1, 1)
        self.Number2Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number2Button.setObjectName("Number2Button")
        self.gridLayout.addWidget(self.Number2Button, 3, 2, 1, 1)
        self.Number7Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Number7Button.setObjectName("Number7Button")
        self.gridLayout.addWidget(self.Number7Button, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Number3Button.setText(_translate("MainWindow", "3"))
        self.Number1Button.setText(_translate("MainWindow", "1"))
        self.SubmitButton.setText(_translate("MainWindow", "SUBMIT"))
        self.ClearButton.setText(_translate("MainWindow", "CLEAR"))
        self.Number9Button.setText(_translate("MainWindow", "9"))
        self.NextButton.setText(_translate("MainWindow", "NEXT"))
        self.Number8Button.setText(_translate("MainWindow", "8"))
        self.DivideButton.setText(_translate("MainWindow", "/"))
        self.MultiplyButton.setText(_translate("MainWindow", "*"))
        self.AdditionButton.setText(_translate("MainWindow", "+"))
        self.SubtractButton.setText(_translate("MainWindow", "-"))
        self.Number4Button.setText(_translate("MainWindow", "4"))
        self.Number6Button.setText(_translate("MainWindow", "6"))
        self.Number5Button.setText(_translate("MainWindow", "5"))
        self.Number2Button.setText(_translate("MainWindow", "2"))
        self.Number7Button.setText(_translate("MainWindow", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
